# Generated by Django 5.2.7 on 2025-10-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Автоматично генерується з назви категорії', max_length=250, unique=True, verbose_name='Слаг'),
        ),
    ]
